languageCode = "en-us"
title = "Dominik's Blog"
baseurl = "https://dinfuehr.github.io/"
theme = "cocoa"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[params]
author = "Dominik Inführ"
email = "dominik.infuehr@gmail.com"
github = "//github.com/dinfuehr"
twitter = "//twitter.com/dinfuehr"

dateform     = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
